### PR TITLE
Refactor conditionals

### PR DESCRIPTION
**Pull request by mbowen13**
I created the function checkConditions() to modularize responses that require conditions. I used the function to modularize some of the existing responses.

You can also use the responseObject to create responses that do not require conditions. I included a few examples in the object.

I also refactored the code for better readability. For example, the stackoverflow search was in the middle of the conditional responses, so I moved it to the end of the bot.on('message') so it has its own space. This way it's less confusing and easier to find corresponding variables and functions due to proper grouping.

### CODE REVIEW

**Comment by Kiri23** [comment]
I push your code to the base project but I can't do this merge because a merge conflict. anyways I did change the master project to reflect your changes.

**Comment by mbowen13** [comment]
No problem. I'll fix the conflicts when I get done with work later.

**Comment by Kiri23** [comment]
I need to test this in my computer. I will merge it when I had the time. : )

**Comment by mbowen13** [comment]
This is going to take forever to fix all the merge conflicts :(

**Comment by Kiri23** [comment]
why ? 🙁

**Comment by mbowen13** [comment]
Because it's so unorganized. It would be better to create separate files for these functions so everything is not chunked into one file. That's what I was going to start one next.

I'm also seeing someone went into the command functions I made and just changed the commands to all be capitalized. Not sure why that was changed?

**Comment by Kiri23** [comment]
Yeah refactoring the code is on my todo list before anything else but some people did some improvement to the code(Like the stackoverflow api and the welcome message) that I want that included on the code before it goes live.

**Comment by mbowen13** [comment]
Would also be a good idea to start writing some tests since there are functions not everyone worked on...good to know if a change breaks another function.

**Comment by Kiri23** [comment]
yeah i know is messy but hopefully will be better organized by the next week and established some rules on how we can contribute it to make the code more safety check and organized. You can give your ideas if you want.

**Comment by mbowen13** [comment]
ok

**Comment by Kiri23** [comment]
Im going to change the command your did back to normal with lowercase

**Pull request closed without merging**
